/**
 * Self-contained login gate for the Command Center.
 *
 * Auth source of truth = two env vars on app-core (loaded via
 * /etc/migrateck/console.env):
 *
 *   CONSOLE_ADMIN_EMAIL=admin@migrateck.com
 *   CONSOLE_ADMIN_PASSWORD_HASH=<output of `node -e "..." scryptSync` — see below>
 *   CONSOLE_SESSION_SECRET=<random 32+ char string used to HMAC-sign cookies>
 *
 * To generate a fresh password hash for storage:
 *   node -e "const c=require('crypto');const s=c.randomBytes(16);const h=c.scryptSync(process.argv[1], s, 64).toString('hex');console.log('scrypt:'+s.toString('hex')+':'+h)" 'THE_PASSWORD'
 *
 * The separator is a COLON. This command previously printed `scrypt$salt$hash`
 * (the `\$` escapes to a literal `$` inside the double-quoted shell string) while
 * the parser has always split on ":" — so a hash generated by following these
 * instructions could never validate, with no diagnostic beyond a failed login.
 * password-hash.test.ts now executes this exact command and feeds its output to
 * the real parser, so the two cannot drift apart again.
 *
 * Verification uses crypto.timingSafeEqual to prevent timing attacks.
 */

import { cookies } from "next/headers";
import crypto from "node:crypto";
import { SESSION_COOKIE_NAME, SESSION_COOKIE_PATH } from "./session-cookie";
import { verifyScryptHash } from "./password-hash";

const COOKIE_NAME = SESSION_COOKIE_NAME;
const SESSION_TTL_SECONDS = 60 * 60 * 12; // 12 hours

type SessionPayload = {
  email: string;
  iat: number; // issued-at (unix seconds)
  exp: number; // expiry (unix seconds)
};

const getSecret = () => {
  const s = process.env.CONSOLE_SESSION_SECRET;
  if (!s || s.length < 24) {
    // Production should always have a strong secret. Refuse to issue sessions
    // if one isn't configured.
    throw new Error("CONSOLE_SESSION_SECRET not configured (must be ≥24 chars).");
  }
  return s;
};

const sign = (data: string, secret: string) =>
  crypto.createHmac("sha256", secret).update(data).digest("base64url");

const safeEqual = (a: string, b: string) => {
  const ab = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ab.length !== bb.length) return false;
  return crypto.timingSafeEqual(ab, bb);
};

const encode = (payload: SessionPayload, secret: string): string => {
  const body = Buffer.from(JSON.stringify(payload)).toString("base64url");
  return `${body}.${sign(body, secret)}`;
};

const decode = (raw: string, secret: string): SessionPayload | null => {
  const [body, sig] = raw.split(".");
  if (!body || !sig) return null;
  const expected = sign(body, secret);
  if (!safeEqual(sig, expected)) return null;
  try {
    const payload = JSON.parse(Buffer.from(body, "base64url").toString("utf8")) as SessionPayload;
    if (!payload.exp || payload.exp < Math.floor(Date.now() / 1000)) return null;
    return payload;
  } catch {
    return null;
  }
};

export const verifyPassword = (plain: string): boolean =>
  verifyScryptHash(plain, process.env.CONSOLE_ADMIN_PASSWORD_HASH || "");

export const verifyEmail = (email: string): boolean => {
  const allowed = (process.env.CONSOLE_ADMIN_EMAIL || "").trim().toLowerCase();
  return Boolean(allowed) && email.trim().toLowerCase() === allowed;
};

export const issueSession = async (email: string): Promise<void> => {
  const now = Math.floor(Date.now() / 1000);
  const payload: SessionPayload = {
    email,
    iat: now,
    exp: now + SESSION_TTL_SECONDS,
  };
  const value = encode(payload, getSecret());
  const store = await cookies();
  store.set(COOKIE_NAME, value, {
    httpOnly: true,
    secure: true,
    sameSite: "lax",
    path: SESSION_COOKIE_PATH,
    maxAge: SESSION_TTL_SECONDS,
  });
};

export const clearSession = async (): Promise<void> => {
  const store = await cookies();
  // The session cookie is set with path "/console" (see issueSession). A bare
  // delete(name) targets the default path "/" and leaves the "/console"-scoped
  // cookie intact — so we must expire it at the EXACT same path/attributes.
  store.set(COOKIE_NAME, "", {
    httpOnly: true,
    secure: true,
    sameSite: "lax",
    path: SESSION_COOKIE_PATH,
    maxAge: 0,
    expires: new Date(0),
  });
};

export const getSession = async (): Promise<SessionPayload | null> => {
  let secret: string;
  try {
    secret = getSecret();
  } catch {
    return null;
  }
  const store = await cookies();
  const raw = store.get(COOKIE_NAME)?.value;
  if (!raw) return null;
  return decode(raw, secret);
};

export const isConfigured = () =>
  Boolean(
    process.env.CONSOLE_ADMIN_EMAIL &&
      process.env.CONSOLE_ADMIN_PASSWORD_HASH &&
      process.env.CONSOLE_SESSION_SECRET,
  );
