/**
 * Exact JavaScript executed by the Agent Mode webview.
 *
 * This module intentionally has no VS Code dependency so the generated script
 * can be compiled and validated in the plain Node unit-test environment.
 *
 * String.raw preserves escape sequences such as \\n as JavaScript source
 * instead of converting them into literal line breaks inside quoted strings.
 */
export function agentModeWebviewScript(): string {
  return String.raw`const vscode=acquireVsCodeApi();const $=id=>document.getElementById(id);let current;
$('enter').onclick=()=>vscode.postMessage({type:'enter'});$('exit').onclick=()=>vscode.postMessage({type:'exit'});
	$('propose').onclick=()=>vscode.postMessage({type:'propose',recipe:$('recipe').value,reason:$('reason').value});
for(const id of ['approve','reject','cancel','reconcile','recovery','repropose','history','historyDetail','exportEvidence']) $(id).onclick=()=>vscode.postMessage({type:id});
	addEventListener('message',({data})=>{if(data.type==='mode'){ $('mode').textContent=data.enabled?'ON · '+data.state:'OFF';$('mode').className='badge'+(data.enabled?'':' off');$('proposal').style.display=data.enabled?'block':'none';}if(data.type==='error')$('error').textContent=data.message;if(data.type==='history')$('historyBox').textContent=data.text;if(data.type==='recovery'&&current){current.recovery={classification:data.status.recoveryClass,eligible:data.status.eligible,reason:data.status.explanation,sourceRunId:data.status.lineage.sourceRunId,successorRunId:data.status.lineage.successorRunId};render(current,data.status);}if(data.type==='run'){current=data.view;$('error').textContent='';render(current);}});
function render(v,status){$('controls').style.display='block';const p=v.preview;const lines=['State: '+v.state,'Run: '+v.runId,'Request: '+v.requestId];if(p){lines.push('Recipe: '+p.recipe,'Policy: '+p.policyVersion,'Execution identity: '+p.executionIdentity,'Environment policy: '+p.environmentPolicy,'Workspace material: '+p.workspaceMaterialFingerprint,'Snapshot: '+p.snapshotId,'Live source: '+p.sourceWorkspace,'Executable: '+p.executable,...p.arguments.map((a,i)=>'Arg '+(i+1)+': '+a),'Working directory: '+p.cwd,'Timeout: '+p.timeoutMs+' ms','Output limit: '+p.outputLimitBytes+' bytes','Mutation: '+p.mutationClassification,'Network: '+p.networkPolicy,'Can modify files: '+p.canModifyFiles,'Reason: '+p.reason,'Fingerprint: '+p.fingerprint,'Expires: '+new Date(p.expiresAt).toISOString(),...p.expectedEffects.map(e=>'Expected effect: '+e),...p.environment.map(e=>'Environment '+e.key+': '+e.value),...p.warnings.map(w=>'Warning: '+w));}if(v.approval){lines.push('Approval lifecycle: '+v.approval.lifecycle);if(v.approval.invalidationReason)lines.push('Approval invalidation: '+v.approval.invalidationReason);}if(v.recovery){lines.push('Recovery: '+v.recovery.classification,'Recovery eligible: '+v.recovery.eligible);if(v.recovery.reason)lines.push('Recovery reason: '+v.recovery.reason);if(v.recovery.sourceRunId)lines.push('Recovery source: '+v.recovery.sourceRunId);if(v.recovery.successorRunId)lines.push('Recovery successor: '+v.recovery.successorRunId);}if(status)lines.push('Recovery recommendation: '+status.recommendedAction);if(v.result)lines.push('Exit code: '+v.result.exitCode,'stdout: '+v.result.stdout,'stderr: '+v.result.stderr);if(v.error)lines.push('Failure: '+v.error.code+' — '+v.error.message);$('details').textContent=lines.join('\n');$('approve').disabled=v.state!=='AWAITING_APPROVAL';$('reject').disabled=v.state!=='AWAITING_APPROVAL';$('cancel').disabled=!['PLANNING','AWAITING_APPROVAL','APPROVED','EXECUTING'].includes(v.state);$('repropose').disabled=!(v.recovery&&v.recovery.eligible);}
`;
}
