import type { FirewallTemplate } from "@/lib/vps/firewall/types";

const adminCidr = process.env.VPS_ADMIN_CIDR || "0.0.0.0/0";

export const firewallTemplates: FirewallTemplate[] = [
  {
    slug: "secure-ssh-only",
    name: "Secure SSH Only",
    description: "Allow SSH from the admin CIDR and deny all other inbound traffic.",
    state: {
      profileName: "Secure SSH Only",
      inboundDefaultAction: "DENY",
      outboundDefaultAction: "ALLOW",
      antiLockoutEnabled: true,
      rollbackWindowSec: 120,
      rules: [
        {
          direction: "INBOUND",
          action: "ALLOW",
          protocol: "TCP",
          portStart: 22,
          portEnd: 22,
          sourceCidr: adminCidr,
          description: "SSH",
          priority: 100,
          isEnabled: true,
        },
      ],
    },
  },
  {
    slug: "standard-web-server",
    name: "Standard Web Server",
    description: "SSH from admin CIDR plus HTTP and HTTPS from the public internet.",
    state: {
      profileName: "Standard Web Server",
      inboundDefaultAction: "DENY",
      outboundDefaultAction: "ALLOW",
      antiLockoutEnabled: true,
      rollbackWindowSec: 120,
      rules: [
        {
          direction: "INBOUND",
          action: "ALLOW",
          protocol: "TCP",
          portStart: 22,
          portEnd: 22,
          sourceCidr: adminCidr,
          description: "SSH",
          priority: 100,
          isEnabled: true,
        },
        {
          direction: "INBOUND",
          action: "ALLOW",
          protocol: "TCP",
          portStart: 80,
          portEnd: 80,
          sourceCidr: "0.0.0.0/0",
          description: "HTTP",
          priority: 200,
          isEnabled: true,
        },
        {
          direction: "INBOUND",
          action: "ALLOW",
          protocol: "TCP",
          portStart: 443,
          portEnd: 443,
          sourceCidr: "0.0.0.0/0",
          description: "HTTPS",
          priority: 300,
          isEnabled: true,
        },
      ],
    },
  },
  {
    slug: "reverse-proxy-node",
    name: "Reverse Proxy Node",
    description: "Reverse proxy friendly ingress with SSH and TLS ports open.",
    state: {
      profileName: "Reverse Proxy Node",
      inboundDefaultAction: "DENY",
      outboundDefaultAction: "ALLOW",
      antiLockoutEnabled: true,
      rollbackWindowSec: 120,
      rules: [
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 22, portEnd: 22, sourceCidr: adminCidr, description: "SSH", priority: 100, isEnabled: true },
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 80, portEnd: 80, sourceCidr: "0.0.0.0/0", description: "HTTP", priority: 200, isEnabled: true },
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 443, portEnd: 443, sourceCidr: "0.0.0.0/0", description: "HTTPS", priority: 300, isEnabled: true },
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 8443, portEnd: 8443, sourceCidr: adminCidr, description: "Admin proxy", priority: 400, isEnabled: true },
      ],
    },
  },
  {
    slug: "mail-server",
    name: "Mail Server",
    description: "Open SMTP, IMAP, POP3, and submission ports with SSH protection.",
    state: {
      profileName: "Mail Server",
      inboundDefaultAction: "DENY",
      outboundDefaultAction: "ALLOW",
      antiLockoutEnabled: true,
      rollbackWindowSec: 120,
      rules: [
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 22, portEnd: 22, sourceCidr: adminCidr, description: "SSH", priority: 100, isEnabled: true },
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 25, portEnd: 25, sourceCidr: "0.0.0.0/0", description: "SMTP", priority: 200, isEnabled: true },
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 587, portEnd: 587, sourceCidr: "0.0.0.0/0", description: "Submission", priority: 300, isEnabled: true },
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 993, portEnd: 993, sourceCidr: "0.0.0.0/0", description: "IMAPS", priority: 400, isEnabled: true },
      ],
    },
  },
  {
    slug: "private-db",
    name: "Private DB",
    description: "Permit SSH and internal-only database access.",
    state: {
      profileName: "Private DB",
      inboundDefaultAction: "DENY",
      outboundDefaultAction: "ALLOW",
      antiLockoutEnabled: true,
      rollbackWindowSec: 120,
      rules: [
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 22, portEnd: 22, sourceCidr: adminCidr, description: "SSH", priority: 100, isEnabled: true },
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 5432, portEnd: 5432, sourceCidr: "10.0.0.0/8", description: "PostgreSQL internal", priority: 200, isEnabled: true },
      ],
    },
  },
  {
    slug: "allow-internal-only",
    name: "Allow Internal Only",
    description: "Allow SSH and private network access only.",
    state: {
      profileName: "Allow Internal Only",
      inboundDefaultAction: "DENY",
      outboundDefaultAction: "ALLOW",
      antiLockoutEnabled: true,
      rollbackWindowSec: 120,
      rules: [
        { direction: "INBOUND", action: "ALLOW", protocol: "TCP", portStart: 22, portEnd: 22, sourceCidr: adminCidr, description: "SSH", priority: 100, isEnabled: true },
        { direction: "INBOUND", action: "ALLOW", protocol: "ANY", sourceCidr: "10.0.0.0/8", description: "Private network", priority: 200, isEnabled: true },
      ],
    },
  },
  {
    slug: "custom-empty",
    name: "Custom Empty",
    description: "Start from an empty draft with rollback protection enabled.",
    state: {
      profileName: "Custom Empty",
      inboundDefaultAction: "DENY",
      outboundDefaultAction: "ALLOW",
      antiLockoutEnabled: true,
      rollbackWindowSec: 120,
      rules: [],
    },
  },
];
