-- ─────────────────────────────────────────────────────────────────────
-- Per-client account-security return destination
--
-- WHY THIS COLUMN EXISTS. Changing a password now ends the session on purpose:
-- a stored credential is not a working one until it has signed someone in. That
-- leaves MigraAuth holding a person it must send somewhere, and the only honest
-- destination is the product they came from — which then starts its own
-- authorization and lands them back where they were.
--
-- MIGRAAUTH CANNOT MINT THAT AUTHORIZATION ITSELF. A transaction is bound to a
-- PKCE `code_challenge` and the client's own `state`, generated by the PRODUCT
-- and held only by it; a code issued against a transaction MigraAuth invented is
-- rejected by the product's own callback. So the product must begin the request,
-- and this column names where to send someone so that it does.
--
-- IT IS NOT DERIVABLE. `default_post_login_url` is where a product wants people
-- AFTER signing in, not how a sign-in starts, and the sign-in entry differs per
-- product (`/api/auth/login` vs `/auth/callback` conventions already diverge in
-- this table). Guessing a path produces a URL that answers an arriving visitor
-- with an error instead of a sign-in.
--
-- TRUSTED BECAUSE IT IS REGISTRY STATE, NOT BROWSER STATE. The browser never
-- supplies it. Its ORIGIN is additionally required to match one the client
-- already proved it owns — a registered redirect URI or `default_post_login_url`
-- — so even a mistyped row cannot become an open redirect to another host.
--
-- NULLABLE, and null means "send them to the product's origin, or to MigraAuth's
-- own login" — exactly the behaviour that shipped before this column, so every
-- existing client keeps working untouched.
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE oauth_clients
  ADD COLUMN IF NOT EXISTS account_return_url VARCHAR(500) NULL;

COMMENT ON COLUMN oauth_clients.account_return_url IS
  'Where MigraAuth sends someone after an account-security action that ends their session (password set/change). Should be the product''s SIGN-IN entry carrying its own post-login destination, e.g. https://app.example.com/api/auth/login?next=/settings — the product starts a fresh PKCE authorization and returns the person there. Its origin MUST match a registered redirect URI or default_post_login_url; MigraAuth refuses it otherwise.';
