#!/bin/bash
#
# sync-mail-configs.sh
# Automatically generates mail server configs from panel-api .env
# Safe for automated execution via cron
#
# Usage: ./sync-mail-configs.sh [--dry-run] [--force]
#

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Flags
DRY_RUN=false
FORCE=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        *)
            echo "Usage: $0 [--dry-run] [--force]"
            exit 1
            ;;
    esac
done

# Configuration
PANEL_API_HOST="root@100.119.105.93"
PANEL_API_ENV="/opt/MigraPanel/apps/panel-api/.env"
POSTFIX_CONFIG_DIR="/etc/postfix/sql"
DOVECOT_CONFIG="/etc/dovecot/dovecot-sql.conf.ext"
BACKUP_DIR="/etc/mail-configs-backups"

log() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Extract credentials
extract_db_credentials() {
    log "Extracting database credentials from $PANEL_API_HOST:$PANEL_API_ENV"
    
    # Fetch .env from remote panel-api server
    local db_url=$(ssh "$PANEL_API_HOST" "grep '^DATABASE_URL=' '$PANEL_API_ENV' 2>/dev/null || echo ''" | cut -d'=' -f2- | tr -d '"' | tr -d "'")
    
    if [ -z "$db_url" ]; then
        error "DATABASE_URL not found in $PANEL_API_HOST:$PANEL_API_ENV"
        exit 1
    fi
    
    DB_USER=$(echo "$db_url" | sed -n 's|.*://\([^:]*\):.*|\1|p')
    DB_PASS=$(echo "$db_url" | sed -n 's|.*://[^:]*:\([^@]*\)@.*|\1|p')
    DB_HOST=$(echo "$db_url" | sed -n 's|.*@\([^:]*\):.*|\1|p')
    DB_PORT=$(echo "$db_url" | sed -n 's|.*:\([0-9]*\)/.*|\1|p')
    DB_NAME=$(echo "$db_url" | sed -n 's|.*/\([^?]*\).*|\1|p')
    
    log "Extracted credentials: user=$DB_USER, host=$DB_HOST:$DB_PORT, db=$DB_NAME"
}

# Create backups
create_backups() {
    mkdir -p "$BACKUP_DIR"
    local timestamp=$(date +%Y%m%d_%H%M%S)
    
    log "Creating backups in $BACKUP_DIR/$timestamp/"
    mkdir -p "$BACKUP_DIR/$timestamp"
    
    cp -p "$POSTFIX_CONFIG_DIR"/*.cf "$BACKUP_DIR/$timestamp/" 2>/dev/null || true
    cp -p "$DOVECOT_CONFIG" "$BACKUP_DIR/$timestamp/" 2>/dev/null || true
    
    log "Backups created"
}

# Generate Postfix virtual_aliases.cf
generate_postfix_aliases() {
    cat > "${POSTFIX_CONFIG_DIR}/virtual_aliases.cf" <<EOF
# Auto-generated by sync-mail-configs.sh
# Source: panel-api DATABASE_URL
# Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')

user = ${DB_USER}
password = ${DB_PASS}
hosts = ${DB_HOST}
dbname = ${DB_NAME}
query = SELECT destination FROM mail_aliases WHERE source = '%s'
EOF
    
    chown postfix:postfix "${POSTFIX_CONFIG_DIR}/virtual_aliases.cf"
    chmod 640 "${POSTFIX_CONFIG_DIR}/virtual_aliases.cf"
}

# Generate Postfix virtual_domains.cf
generate_postfix_domains() {
    cat > "${POSTFIX_CONFIG_DIR}/virtual_domains.cf" <<EOF
# Auto-generated by sync-mail-configs.sh
# Source: panel-api DATABASE_URL
# Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')

user = ${DB_USER}
password = ${DB_PASS}
hosts = ${DB_HOST}
dbname = ${DB_NAME}
query = SELECT domain FROM mail_domains WHERE domain = '%s'
EOF
    
    chown postfix:postfix "${POSTFIX_CONFIG_DIR}/virtual_domains.cf"
    chmod 640 "${POSTFIX_CONFIG_DIR}/virtual_domains.cf"
}

# Generate Postfix virtual_mailboxes.cf
generate_postfix_mailboxes() {
    cat > "${POSTFIX_CONFIG_DIR}/virtual_mailboxes.cf" <<EOF
# Auto-generated by sync-mail-configs.sh
# Source: panel-api DATABASE_URL
# Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')

user = ${DB_USER}
password = ${DB_PASS}
hosts = ${DB_HOST}
dbname = ${DB_NAME}
query = SELECT CONCAT(d.domain, '/', m.localpart, '/') FROM mailboxes m JOIN mail_domains d ON m.domain_id = d.id WHERE m.address = '%s'
EOF
    
    chown postfix:postfix "${POSTFIX_CONFIG_DIR}/virtual_mailboxes.cf"
    chmod 640 "${POSTFIX_CONFIG_DIR}/virtual_mailboxes.cf"
}

# Generate Dovecot config
generate_dovecot_config() {
    cat > "${DOVECOT_CONFIG}" <<EOF
# Auto-generated by sync-mail-configs.sh
# Source: panel-api DATABASE_URL
# Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')

driver = pgsql
connect = host=${DB_HOST} dbname=${DB_NAME} user=${DB_USER} password='${DB_PASS}'

# Password query - returns bcrypt hash (already has \$2y\$ prefix)
password_query = SELECT m.address AS user, m.passwordhash AS password FROM mailboxes m JOIN mail_domains d ON m.domain_id = d.id WHERE m.address = '%u'

# User query - returns maildir path and uid/gid
user_query = SELECT CONCAT('/home/vmail/', d.domain, '/', m.localpart, '/') AS home, CONCAT('maildir:/home/vmail/', d.domain, '/', m.localpart, '/Maildir') AS mail, 5000 AS uid, 5000 AS gid FROM mailboxes m JOIN mail_domains d ON m.domain_id = d.id WHERE m.address = '%u'

# Iterate query for doveadm
iterate_query = SELECT m.address AS user FROM mailboxes m
EOF
    
    chown dovecot:dovecot "${DOVECOT_CONFIG}"
    chmod 640 "${DOVECOT_CONFIG}"
}

# Validate generated configs
validate_configs() {
    log "Validating generated configs..."
    
    # Test Postfix config syntax
    if ! postmap -q "test@migrahosting.com" "pgsql:${POSTFIX_CONFIG_DIR}/virtual_domains.cf" &>/dev/null; then
        warn "Postfix config validation check couldn't connect (expected for test query)"
    fi
    
    # Test database connectivity
    if command -v psql &>/dev/null; then
        if PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1" &>/dev/null; then
            log "Database connectivity verified"
        else
            error "Database connectivity check failed"
            return 1
        fi
    fi
    
    return 0
}

# Reload services
reload_services() {
    if [ "$DRY_RUN" = true ]; then
        log "[DRY-RUN] Would reload: postfix, dovecot"
        return 0
    fi
    
    log "Reloading Postfix..."
    systemctl reload postfix
    
    log "Reloading Dovecot..."
    systemctl reload dovecot
    
    log "Services reloaded successfully"
}

# Main execution
main() {
    echo "==================================="
    echo "Mail Config Sync"
    echo "==================================="
    
    if [ "$DRY_RUN" = true ]; then
        warn "Running in DRY-RUN mode (no changes will be made)"
    fi
    
    # Extract credentials
    extract_db_credentials
    
    # Check if configs need updating
    if [ "$FORCE" = false ] && [ "$DRY_RUN" = false ]; then
        # Run validation first to see if update is needed
        if /opt/migra/scripts/validate-mail-configs.sh &>/dev/null; then
            log "Configs are already up-to-date, no sync needed"
            exit 0
        fi
    fi
    
    if [ "$DRY_RUN" = false ]; then
        # Create backups
        create_backups
        
        # Generate configs
        log "Generating Postfix configs..."
        generate_postfix_aliases
        generate_postfix_domains
        generate_postfix_mailboxes
        
        log "Generating Dovecot config..."
        generate_dovecot_config
        
        # Validate
        if ! validate_configs; then
            error "Config validation failed!"
            exit 1
        fi
        
        # Reload services
        reload_services
        
        echo ""
        log "✓ Mail configs synchronized successfully"
        log "✓ Services reloaded"
        log "Backups saved in: $BACKUP_DIR/"
    else
        log "Would generate configs from DATABASE_URL"
        log "Would create backups"
        log "Would reload services"
    fi
    
    exit 0
}

main
