# HTTP
server {
    listen 80;
    listen [::]:80;
    server_name console.migradrive.com;
    include /etc/nginx/snippets/tenant-suspension.conf;

    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://$host$request_uri; }
}

# HTTPS
server {
    listen 443 ssl;
    include /etc/nginx/snippets/ocsp-off.conf;
    listen [::]:443 ssl;
    server_name console.migradrive.com;
    include /etc/nginx/snippets/tenant-suspension.conf;

    ssl_certificate /etc/letsencrypt/live/console.migradrive.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/console.migradrive.com/privkey.pem;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        include /etc/nginx/snippets/migradrive-console-proxy.conf;
    }
}
