server {
    listen 80;
    server_name console.mb.migrahosting.com;
    include /etc/nginx/snippets/tenant-suspension.conf;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    include /etc/nginx/snippets/ocsp-off.conf;
    server_name console.mb.migrahosting.com;
    include /etc/nginx/snippets/tenant-suspension.conf;
    
    ssl_certificate /etc/letsencrypt/live/console.mb.migrahosting.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/console.mb.migrahosting.com/privkey.pem;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    
    
    location / {
        include /etc/nginx/snippets/migradrive-console-proxy.conf;
    }
}
