import type { PortalRelyingPartyDefinition } from "./types";

// This registry is the single source of truth for first-party portal login targets.
// Product apps should launch central auth based on this map instead of hardcoding
// client ids or callback hosts in scattered route handlers.
export const PORTAL_RELYING_PARTIES: PortalRelyingPartyDefinition[] = [
  {
    key: "migrateck-marketing",
    label: "MigraTeck Web",
    publicHosts: ["migrateck.com", "www.migrateck.com"],
    clientId: "migrateck_web",
    redirectPath: "/auth/callback",
    logoutPath: "/login",
    authority: "central",
    bootstrapAuthority: "product-app",
    redirectStrategy: "same-origin-callback",
  },
  {
    key: "migrahosting-vps-portal",
    label: "MigraHosting VPS Portal",
    publicHosts: ["vps.migrahosting.com"],
    clientId: "migrahosting_web",
    redirectPath: "/auth/callback",
    logoutPath: "/login",
    authority: "central",
    bootstrapAuthority: "product-app",
    redirectStrategy: "same-origin-callback",
  },
  {
    key: "migrahosting-client-portal",
    label: "MigraHosting Client Portal",
    publicHosts: ["control.migrahosting.com"],
    clientId: "migrahosting_client_portal",
    redirectPath: "/api/auth/central/callback",
    logoutPath: "/client/login",
    authority: "central",
    bootstrapAuthority: "panel-api",
    redirectStrategy: "portal-callback-bridge",
  },
  {
    key: "migrapanel-web",
    label: "MigraPanel Web",
    publicHosts: ["migrapanel.com", "panel.migrateck.com"],
    clientId: "migrapanel_web",
    redirectPath: "/auth/callback",
    logoutPath: "/",
    authority: "central",
    bootstrapAuthority: "product-app",
    redirectStrategy: "same-origin-callback",
  },
  {
    key: "migradrive-web",
    label: "MigraDrive Web",
    publicHosts: ["migradrive.com"],
    clientId: "migradrive_web",
    redirectPath: "/auth/callback",
    logoutPath: "/",
    authority: "central",
    bootstrapAuthority: "product-app",
    redirectStrategy: "same-origin-callback",
  },
  {
    key: "migramail-web",
    label: "MigraMail Web",
    publicHosts: ["migramail.com"],
    clientId: "migramail_web",
    redirectPath: "/auth/callback",
    logoutPath: "/",
    authority: "central",
    bootstrapAuthority: "product-app",
    redirectStrategy: "same-origin-callback",
  },
  {
    key: "migravoice-web",
    label: "MigraVoice Web",
    publicHosts: ["migravoice.com"],
    clientId: "migravoice_web",
    redirectPath: "/auth/callback",
    logoutPath: "/",
    authority: "central",
    bootstrapAuthority: "product-app",
    redirectStrategy: "same-origin-callback",
  },
];
