/**
 * Where to send someone after an account-security action ended their session.
 *
 * Its own module, and PURE, because it is a redirect decision: the failure mode
 * is an open redirect, and that is worth testing with adversarial inputs rather
 * than reading carefully once inside a route handler.
 *
 * WHY A REDIRECT IS NEEDED AT ALL. Changing a password now revokes the session
 * on purpose — a stored credential is not a working one until it has signed
 * somebody in. MigraAuth is then holding a person it must send somewhere, and
 * the only honest destination is the product they came from.
 *
 * WHY MIGRAAUTH CANNOT JUST BUILD ONE. An authorization transaction is bound to
 * a PKCE `codeChallenge` and the client's own `state`, generated by the PRODUCT
 * and held only by it. A code issued against a transaction MigraAuth invented is
 * rejected by the product's own callback, which verifies `state` and exchanges
 * with its stored verifier. The product has to start its own request; that is
 * the property PKCE exists for, and routing around it would mean weakening it.
 */

export interface ClientReturnFacts {
  /** The product's SIGN-IN entry, carrying its own post-login destination. */
  accountReturnUrl: string | null;
  defaultPostLoginUrl: string | null;
  redirectUris: unknown;
}

/** `https`, or `localhost` for development. Nothing else names a destination. */
function originOf(value: unknown): string | null {
  if (typeof value !== "string" || value.length === 0) return null;
  try {
    const url = new URL(value);
    if (url.protocol === "https:") return url.origin;
    if (url.protocol === "http:" && url.hostname === "localhost") return url.origin;
    return null;
  } catch {
    return null;
  }
}

/**
 * The origins this client has ALREADY PROVED it owns.
 *
 * Registration validated these. Nothing outside this set may be redirected to,
 * whatever any other column says.
 */
export function ownedOrigins(facts: ClientReturnFacts): Set<string> {
  const origins = new Set<string>();
  const post = originOf(facts.defaultPostLoginUrl);
  if (post) origins.add(post);
  if (Array.isArray(facts.redirectUris)) {
    for (const uri of facts.redirectUris) {
      const origin = originOf(uri);
      if (origin) origins.add(origin);
    }
  }
  return origins;
}

export interface ReturnResolution {
  url: string | null;
  /** Why this answer — surfaced so a misconfiguration is visible, not silent. */
  reason: "configured" | "origin_fallback" | "unowned_origin" | "unusable" | "none";
}

export function resolveAccountReturn(facts: ClientReturnFacts): ReturnResolution {
  const origins = ownedOrigins(facts);

  /*
   * THE CONFIGURED DESTINATION IS THE ONLY VALUE ALLOWED TO CARRY A PATH,
   * because it is the only one that means "start a sign-in here". It is registry
   * state and the browser never supplies it — but it is still checked against
   * the owned origins, so a mistyped row cannot turn a password change into an
   * open redirect. A row that fails is IGNORED, never obeyed.
   */
  if (facts.accountReturnUrl) {
    const configuredOrigin = originOf(facts.accountReturnUrl);
    if (!configuredOrigin) return fallback(facts, origins, "unusable");
    if (!origins.has(configuredOrigin)) return fallback(facts, origins, "unowned_origin");
    return { url: new URL(facts.accountReturnUrl).toString(), reason: "configured" };
  }

  return fallback(facts, origins, "none");
}

/*
 * ORIGIN ONLY, NEVER A REDIRECT URI'S PATH. That path is a callback that expects
 * an authorization code; an arriving visitor gets an error page, not a sign-in.
 * The product's own root will route them to sign in — only the precise return to
 * account settings is lost, which is a degraded answer rather than a broken one.
 */
function fallback(
  facts: ClientReturnFacts,
  origins: Set<string>,
  reason: ReturnResolution["reason"],
): ReturnResolution {
  const preferred = originOf(facts.defaultPostLoginUrl);
  if (preferred && origins.has(preferred)) {
    return { url: preferred, reason: reason === "none" ? "origin_fallback" : reason };
  }
  for (const origin of origins) {
    return { url: origin, reason: reason === "none" ? "origin_fallback" : reason };
  }
  return { url: null, reason: reason === "none" ? "none" : reason };
}
